apiVersion: v1
kind: Pod
metadata: 
 name: empty-dir
 namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: /var/log/nginx
        name: nginx-logs
    - name: almalinux
      image: almalinux:9
      volumeMount: 
      - mountPath: /mnt/nginx-logss
        name: nginx-logs
      command: ["sleep","10000"]
  volumes:
  - name: nginx-logs
    emptyDir:
     sizeLimit: 100mi