apiVersion: v1
kind: Service
metadata:
 name: services
spec:
  type: NodePort
  selector:
   project: roboshop
   component: frontend
   env: dev
   purpose: node-port
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

 