apiVersion: v1
kind: Service
metadata:
 name: nginx
spec:
  type: LoadBalancer
  selector:
   project: roboshop
   component: frontend
   env: dev
   purpose: Load-balancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodeport: 30007

 