apiVersion: v1
kind: Service
metadata:
 name: services
spec:
  type: LoadBalancer
  selector:
    purpose: headless-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-headles
spec:
  clusterIP: None
  selector:
    purpose: rs-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these are replica set labels
  labels:
    purpose: rs-demo
    project: roboshop
spec:
  replicas: 3
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: rs-demo
      project: roboshop
  # pod definition
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx